language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-28
    - sys-img-armeabi-v7a-android-28

  install:
    - echo y | sdkmanager "ndk-bundle"
    - echo y | sdkmanager "cmake;3.6.4111459"
    - echo y | sdkmanager --channel=3 --channel=1 "cmake;3.10.2.4988404"
    - echo y | sdkmanager "lldb;3.1"

  before_script:
    - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle

  script:
      # 生成 APK
      - ./gradlew assembleRelease

  before_cache:
   - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

  cache:
   directories:
   - $HOME/.gradle/caches/
   - $HOME/.gradle/wrapper/